### ISSUE TITLE
Permission to link to this presentation in the drake manual

### ISSUE THREAD

**Issue by wlandau** [DominikRafacz/drake-presentation#1]
@DominikRafacz, thank you for presenting `drake` at the a [satRday](https://gdansk2019.satrdays.org). It really helps that you are spreading the word. May I link to your materials from [this section of the manual](https://ropenscilabs.github.io/drake-manual/index.html#presentations)?

**Comment by DominikRafacz** [comment]
It is a pleasure for me to share information about such a good tool with the world. 
Of course you can link my presentation, if you find it useful.

**Comment by wlandau** [comment]
Thanks! The reference is now up: https://ropenscilabs.github.io/drake-manual/index.html#presentations.
