### ISSUE TITLE
Use of drake_config()

### ISSUE THREAD

**Issue by wlandau** [DominikRafacz/drake-presentation#3]
@DominikRafaczk, I would just like to point out a minor detail on slide 6. Contrary to intuition, problems can arise when you call

```r
vis_drake_graph(drake_config(plan))
```

or

```r
drake_config(plan) %>%
  vis_drake_graph()
```

rather than the more reliable

```r
config <- drake_config(plan)
vis_drake_graph(config)
```

Details: https://github.com/ropensci/drake/issues/163, https://github.com/ropensci/drake/issues/335, https://github.com/ropensci/drake/issues/527, https://github.com/ropensci/drake/issues/874.

**Comment by wlandau** [comment]
To avoid this issue altogether, you can define a `_drake.R` file and use `r_make()` and `r_vis_drake_graph()` instead: https://ropenscilabs.github.io/drake-manual/projects.html#safer-interactivity

**Comment by DominikRafacz** [comment]
Thanks for pointing it out. I'm just learning how to use `drake` and it seems that I need to learn a lot more...
I've changed the code according to your suggestion.

**Comment by wlandau** [comment]
Thanks!
